### ISSUE TITLE
Create a release to be used for conda packages

### ISSUE THREAD

**Issue by abhilesh** [capoony/PoolSNP#10]
Hi, I am building a nextflow pipeline that uses PoolSNP. For each of use across multiple systems, I'd like to package PoolSNP as a conda recipe ([PR at bioconda-recipes](https://github.com/bioconda/bioconda-recipes/pull/49156)) and build containers from that downstream.

Conda policy specifies tying the package to a release number ([see here](https://bioconda.github.io/contributor/linting.html#uses-vcs-url:~:text=consistent%20and%20clean.-,%E2%80%9Cuses_vcs_url%E2%80%9D,tagging%E2%80%9D%20a%20release%20via%20their%20web%20interface%2C%20making%20the%20process%20simple.,-%E2%80%9Cfolder_and_package_name_must_match%E2%80%9D)). If possible, could you please package the stable version of PoolSNP as a release in this repo? I can then directly pull the release in the conda recipe.

**Comment by capoony** [comment]
Dear Abhilesh, 

fantastic idea, I will take care of it tomorrow.

Many thanks, 

Martin

**Comment by abhilesh** [comment]
Thanks a lot for the release! My PR at bioconda-recipes was approved and merged, PoolSNP is now available as a [Conda package](https://anaconda.org/bioconda/poolsnp), [Docker image](https://quay.io/repository/biocontainers/poolsnp) and [Singularity image](https://depot.galaxyproject.org/singularity/poolsnp%3A1.0.0--py312h7e72e81_0)
