### ISSUE TITLE
Using PoolSNP to genotype non-SNP sites

### ISSUE THREAD

**Issue by mshpak76** [capoony/PoolSNP#5]
I am comparing allele frequencies in Poolseq data to individual sequence data sampled at different locations. It's possible that a site which is polymorphic and called as a SNP in the former to be non-polymorphic and not called as a SNP in the latter. For this reason, I need to call poolseq genotypes for non-SNP sites as well, since I can't just assume that they match a reference genome.

I did this by setting min-count=0 so that sites with 0 minor allele counts are also returned. This returns genotypes for some non-SNP sites, but far fewer than I would expect given the read depth and coverage of the data. I would guess that only 10% or so of genotypes are called.

I know that PoolSNP is optimized for variant calling, but surely there's some way to get to to return a vcf with allele frequency counts at all sites rather than just the SNPs, as can be done with GATK. Is there something I need to do other than set min-count to 0? I think that the poolsnp.py code contains various checks to determine whether there is more than a single allele, but it's not immediately clear to me if there's a simple modification that would return genotypes at all sites with mind-cov greater than the set threshold.

The commands I used are appended below:

$pool_snp_path/PoolSNP.sh \
mpileup=$sample_path/SRR_Realign_AllFiles.mpileup \
reference=$ref_path/DmelRef.fasta \
names=$names \
max-cov=0.98 \
min-cov=5 \
min-count=0 \
min-freq=0 \
miss-frac=0.5\
jobs=0 \
BS=0 \
output=$out_path/All_Files_SRR_SNP_AllSites

**Comment by capoony** [comment]
Hi Max, please apologize my horribly delayed response. 

I have now added a new feature to report all sites irrespective of whether a position is polymorphic or not. You need to set allsites=1 in the command. See also the update README

I hope this is not coming far too late for you!

Cheers, Martin
