### ISSUE TITLE
Sample order

### ISSUE THREAD

**Issue by tvdwbar** [capoony/PoolSNP#6]
Samtools mpileup does not retain sample names, hence PoolSNP allows to specifiy sample names. However, in what order? My input into samtools was *.bam on a folder containing my bam files. Is the sample order inexplicitly contained in the mpileup the same as 'ls *.bam' on the folder?

**Comment by capoony** [comment]
Hi, sorry for my late response! 

Usually when creating an mpileup file from many BAM files you pass the path of the input files to samtools in the form  of a bamfile list, e.g. by 

`echo /inputfolder/*.bam > bamlist` 
and 
`samtools mpileup -b bamlist > output.mpileup`

The sample columns in the samtools mpileup output will be ordered according to the top to bottom order of BAM files in the bamlist. PoolSNP retains the order of the columns in the mpileup file.

Hope this is helpful, 

Cheers, Martin

**Comment by tvdwbar** [comment]
Great, that is good to know! Very helpful, thanks,
